project:
  type: website

website:
  title: "ANTH151"
  site-url: "https://cusisom.github.io/ANTH151/"
  repo-url: "https://github.com/cusisom/ANTH151"
      
  sidebar:
    style: "docked"
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
        
      - section: "Unit 1: Human Evolution"
        collapse-level: 1
        contents:
          - href: "Unit 1/Evolution.qmd"
            text: "Wk 1. Evolution"
        
      - section: "Unit 2: Ancient Migrations"
        collapse-level: 1
        contents:
          - href: "Unit 2/Temporal.qmd"
            text: "Wk 7. Temporal Context"
          - href: "Unit 2/Climate.qmd"
            text: "Wk. 8 Environmental Context"
          - href: "Unit 2/North_America.qmd"
            text: "Wk 10.Peopling of the Americas"
        
      - section: "Unit 3: Civilization"
        collapse-level: 1
        contents:
          - href: index.qmd
            text: "Unit 3 Coming Soon"

format:
  html:
    bibliography: references.bib
    include-in-header: header.html
    tbl-cap-location: bottom
    theme:
      - minty
    grid:
      margin-width: 0px
      body-width: 1200px
    css: styles.css
    from: markdown+emoji
    toc: true
    toc-title: Contents
    toc-location: left

